### ISSUE TITLE
Unfriendly error messages

### ISSUE THREAD

**Issue by hasIan** [metaverse/truss#107]
While trying to run Truss earlier today, I got this error message. I think I would have understood more, though, if it just crashed.

> cannot parse input definition proto files: cannot create svcdef: error parsing service "HelloServiceClient": Couldn't create service method "SayHello" of service "HelloServiceClient": RequestType creation of service method "SayHello" failed: could not create FieldType, star.Type is not *ast.Ident

😠 

This is a general call to producing more useful error messages for users. Sending a four-level deep error back to the error and vomiting it onto the CLI may in fact do more harm than good. We need to "interpret" the errors that bubble up from lower levels and not just necessarily `errors.Wrap` them, lest we end up merely with a stacktrace as a string with no filenames and line numbers.

**Comment by hasAdamr** [comment]
Could you give steps to reproduce?

**Comment by hasIan** [comment]
Unfortunately, I have no idea what I did to get this error message; I was trying to put together a slapdash presentation and trying to build the simplest example I could, and got this error message. Any recollection of the context was wiped away by the need to get something working in a matter of minutes. I'll try a couple things, but am not sure I'll be able to reproduce it. But reproduction isn't the most important thing here--the point is that the default manner of "handling" errors in most software projects is to pass it up the chain until it reaches the top, which explodes with whatever has been passed up. And as we can see here, it yields something that is no help whatsoever. Our blind adherence to the church of `errors.Wrap` does us a disservice here.

**Comment by hasIan** [comment]
It's not something that I expect a concentrated effort to "fix" this, but as we evolve the project, we should keep this sort of thing in mind.

**Comment by hasAdamr** [comment]
I can quickly add a `-v` or `--verbose` flag so that `github.com/pkg/errors` will print out the stack trace, files, and line numbers that caused the errors. For a developer, that error provides a lot of context.

Adding the line numbers is the difference between `fmt.Println("%v\n", err)` and `fmt.Println("%+v\n", err)`.

**Comment by hasAdamr** [comment]
@hasLeland Please look into adding context that could help the user into the error that Ian got as the root post of this issue. Seems the errors.Wrap was used to add context, but not context that would be helpful to a user to fix their .proto file.

**Comment by hasIan** [comment]
I'm thinking it might have been caused by something incorrect in my .proto file, although it didn't complain overtly about the parsing. I was cribbing off the GRPC getting started example, but didn't copy it outright since I had some types defined already, IIRC. Sorry that I cannot recall exactly what led to this message being displayed. But again, maybe this doesn't belong specifically as an "issue" but as a "keep this in mind" as we go forward.

**Comment by hasIan** [comment]
## You can skip to the next comment
**But I'm leaving this for historical integrity**

I got it again, just now:

```
➜  currencyexchangepb git:(retruss_currexch) ✗ $HOME/go/bin/truss -svcout github.com/TuneLab/mv-universe-v2/services/currency-exchange service.proto
```
> cannot parse input definition proto files: cannot create svcdef: error parsing service "CurrencyExchangeServiceClient": Couldn't create service method "ExchangeRateGetRate" of service "CurrencyExchangeServiceClient": RequestType creation of service method "ExchangeRateGetRate" failed: could not create FieldType, star.Type is not *ast.Ident

From this truss:
```
truss (version: f610ad57bb built: 2016-12-08 01:11:15 UTC)
```
(This is the latest version after merging PR #112)

The `proto` files I'm running against are in this [gist](https://gist.github.com/67dc4a9407e3bd5279ef32a032b1b316).

Swapping the options to specify the `pbout` location doesn't help:
```
➜  currency-exchange git:(retruss_currexch) ✗ $HOME/go/bin/truss -pbout github.com/TuneLab/mv-universe-v2/interface-defs/currencyexchangepb ../../interface-defs/currencyexchangepb/service.proto
```
> cannot parse input definition proto files: cannot create svcdef: error parsing service "CurrencyExchangeServiceClient": Couldn't create service method "ExchangeRateGetRate" of service "CurrencyExchangeServiceClient": RequestType creation of service method "ExchangeRateGetRate" failed: could not create FieldType, star.Type is not *ast.Ident

Copying the proto files into the directory where I want the service to be generated and running it there with no command line options to truss (except `service.proto`) yields the same error.

**Comment by hasIan** [comment]
# WAIT!

This is the error you get, apparently, if you run truss only on the "root" `proto` file in this case. Which, here, is `service.proto`. `service.proto` `import`s `exchange_rate.proto`, but truss doesn't care about that, which is a problem because it doesn't run `protoc` on the `import`ed `proto` files. I imagine this is really `protoc`'s issue, but it threw me off. When I make sure the package names match in all `proto` files (which was my first issue), and run truss with `*.proto`, it works, in the first form presented above (i.e., with the `-svcout` option).

So, this error message, in this case anyway, is a very obfuscated way of telling me that it doesn't know one of the types that's being referenced. We should make this more clear.

Additionally, I think this adds to the merit that truss should scan the current directory for `*.proto` for the set of proto files to operate on if no proto files are specified on the command line.

**Comment by hasLeland** [comment]
@hasIan It's actually worse than that.

Right now, the parser for service definitions is very dumb. It's assuming a very strict format for go code that's passed to it as `.pb.go` files.

This bug is actually pointing out that the issue is that the protobuf-to-go program which we use to create the `.pb.go` files may generate legal and useful `pb.go` files that could theoretically be used together, but which truss does not understand or does not expect. And it'd be pretty hard to derive that your problem was the cause of that *very specific* error other than just convention.

So, I'm going to add the empirical debug information that I can (file and line-number information) to the error messages. Then, I'm going to add some "conventional suggestions" to some of the error messages higher up the chain. I'll have a pull request soon.

**Comment by hasAdamr** [comment]
@hasLeland, did that pull request ever go up? 

> I'll have a pull request soon.

Non-critical of course, this does not take priority over other things. Just doing issue cleaning and want to know if this is done / in-progress.

**Comment by adamryman** [comment]
This is a catch all issue, and I'm closing it as a result. More specific issues can be opened if needed.
