### ISSUE TITLE
Alter integration tests to not be environment-dependent

### ISSUE THREAD

**Issue by hasIan** [metaverse/truss#124]
The integration tests run `truss` from wherever it is found in the PATH. The tests (including integration tests), should be more tightly constrained to test what is in the working directory and not be affected much by the environment in which it's running.

## Backstory
In my case, I use GVM to manage my Go versions, which sets up separate `GOPATH`s for each Go version (which I think is dumb, at least for my use case--I'm not using it like a Python virtualenv or anything). As such, I alter my GOPATH to point back to my original, pre-GVM one (`$HOME/go/bin`), but GVM also changes the PATH to put its version-specific `$GOPATH/bin` directory at the head of the path. This meant that running `go install` in the Truss directory was placing binaries into `$HOME/bin`, but the integration tests, when relying on the shell to resolve binaries by searching the PATH, were finding--in this case--truss binaries in `$HOME/.gvm/pkgsets/go1.7.4/global/bin`. So the integration tests were running an outdated binary.

## Proposal
Build truss binaries in the integration-test directory and run it explicitly. However, during truss' run, it in turn invokes the protocast binary, which apparently it finds through the PATH. So some more thought is required here.

## In Conclusion
This is not something that should happen often, but it is a slight vulnerability and I just got bit by it. Aiming to isolate our build and test phases from any environmental inconsistencies will serve us well.

**Comment by hasAdamr** [comment]
This also begs the question about `protoc-gen-go` and `protoc-gen-truss-protocast`. Should these binaries also be built for these tests? They are also required for running the integration tests. 

I vote `protoc-gen-truss-protocast`and `truss` should be built for the tests and `protoc` and `protoc-gen-go` should use the ones in the `$PATH`. As we maintain the code for the former but not the latter.

**Comment by hasIan** [comment]
Agreed 100%. If necessary, we can add something to a FAQ to be mindful of your PATH, if you're not check your path to ensure the expected `protoc` and `protoc-gen-go` binaries are being run, if someone is having oddness with truss.

Separately, and addressing the "needs more thought" issue in the original description, to eliminate the environment dependency, we may need to add a flag to truss, or an undocumented environment variable. It can control what binary is invoked for `protoc-gen-truss-protocast`, if there's a way we can pass that on to `protoc`, or, if not, we can manipulate the PATH in the environment provided to the `protoc` subprocess such that the appropriate version of `protoc-gen-truss-protocast` is found first.

**Comment by hasLeland** [comment]
I sat down to look at implementing this, and the first thing that sprang to mind was simply to build local versions of `truss` and `protoc-gen-truss-protocast` in a set directory, then add that directory to the front of the `PATH` environment variable before the tests are run. Kind of like a more "global" approach to what @hasIan mentioned above about calling `protoc`. You can see an implementation of this [in a branch I made here.](https://github.com/hasLeland/go-truss/commit/d360742bbc96302dce7c271a5aa9daa3381509c9)

Thoughts on doing it that way?

**Comment by hasAdamr** [comment]
@hasLeland, that seems fine to me. Simple, makes the test code itself more flexable as it does not have to reference a specific path, it just calls the first one in the path.
