### ISSUE TITLE
Proposal: New file structure

### ISSUE THREAD

**Issue by adamryman** [metaverse/truss#166]
Current:
```
.
├── docs
├── generated
│   ├── cli
│   │   └── handlers
│   └── client
│       ├── grpc
│       └── http
├── handlers
│   └── server
├── middlewares
├── NAME-cli-client
└── NAME-server

```
New:
```
.
├── docs
├── handlers
├── middlewares
├── NAME-cli-client
├── NAME-server
└── svc
    ├── cli
    │   └── handlers
    └── client
        ├── grpc
        └── http
```

Reasons: 
1. `handlers/server/` is from the time when there were multiple directories in `handlers`.
2. `svc` is the name of the package that gets created inside `generated`. `svc` is distinctive and the documentation can mention this is where generated code lives.
3. Shorter to get to `handlers`. Plus `package handler` can be renamed to `handlers` to match directory.

In addition, rename
```
handlers/server/server_handler.go -> handlers/handlers.go
generated/cli/handlers/client_handler.go -> svc/cli/handlers/handlers.go

NAME-cli-client/client_main.go -> NAME-cli-client/main.go
NAME-server/server_main.go -> NAME-server/main.go
```

**Comment by zaquestion** [comment]
:+1: In favor of the proposed with a few possible tweaks

Seems like cli implies client and we could drop that suffix
```
NAME-cli
```

Not sure how I feel about `svc` replacing `generated`, makes sense to match the package, but feels like we are missing the descriptive nature of the folder name. Granted this folder will be in the import path for http/grpc clients. I think the rest of the folder structure is straightforward enough that `svc` should be self explanatory and a peak inside should clear up any wonder.

I'm still generally in favor of keeping code thats overwritten on each run of truss split off to discourage editing it. For the sake of this proposal however, I think its worth mentioning that we could ditch that model.
Consider
```
.
├── docs
├── handlers
├── middlewares
├── NAME-cli
    ├── cli
    │   └── handlers
├── NAME-server
├── client
    ├── grpc
    └── http
```
We could decorate the files with something like what protoc does and even place readmes in the folders.
```
// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!
```
Again just getting the idea out, I'm not really sure about this approach.
Would yield imports like
```
import "github.com/tunelab/project/project-service/client/http"
```
vs (looking at it, actually svc seems pretty o-kay)
```
import "github.com/tunelab/project/project-service/generated/client/http"
import "github.com/tunelab/project/project-service/svc/client/http"
```

**Comment by adamryman** [comment]
@zaquestion, per in person discussion:

```
NAME-cli
```
:+1:

Otherwise `svc` seems like a pretty good name, and there are files in there that we would need to put somewhere anyways. So I am gonna go with that.

As for the 
```
// Code generated by truss.
// Rerunning truss will overwrite this file.
// DO NOT EDIT!
```

I think I can sneak that into the right places.

**Comment by adamryman** [comment]
Per in person:
@zaquestion @hasIan 
```
NAME-cli-client -> NAME
```

**Comment by adamryman** [comment]
Moving `NAME` and `NAME-server` into a `cmd` directory.

```
.
├── cmd
│   ├── NAME
│   └── NAME-server
├── handlers
├── middlewares
└── svc
    ├── cli
    │   └── handlers
    └── client
        ├── grpc
        └── http
```
