### ISSUE TITLE
Using binary distribution of protoc may cause include problems

### ISSUE THREAD

**Issue by hasLeland** [metaverse/truss#17]
Using a binary distribution of `protoc` instead of compiling it from source may cause an issue in that the default `.proto` files distributed with `protoc` may not be installed in the default location of `/usr/include` or `/usr/local/include`. If the default `.proto` files aren't there, then `protoc` will barf huge amounts of error codes due to some of those default proto files being included in `annotations.proto`.

A quick solution for this would be for us to package those default `.proto` files with truss, probably in the same file tree where we currently store `annotations.proto`:

```
truss/template/service/DONOTEDIT/third_party/googleapis/google/
```

We can get these default proto files by downloading a binary distribution of `protoc`, then copying all the files in the archives `include/` folder into our file tree.

**Comment by hasAdamr** [comment]
This was fixed with Pull Request #35
