### ISSUE TITLE
Can't use imported messages directly in request messages

### ISSUE THREAD

**Issue by pauln** [metaverse/truss#205]
Attempting to use imported messages directly in a request message results in the following error:

```
[33mWARN[0m[0000] Code formatting error, generated service will not build, outputting unformatted code  [33merror[0m=83:3: expected 'IDENT', found '%' (and 10 more errors)
```

If you wrap the imported message, the error goes away.  There is no such error when using imported messages directly in response messages.

Non-working example:

```proto
// input.proto
syntax = "proto3";
package input;

message Data {
    string Content = 1;
}
```

```proto
// echo.proto
syntax = "proto3";
package echo;

import "github.com/TuneLab/truss/deftree/googlethirdparty/annotations.proto";
import "input.proto";

service Echo {
  rpc Echo (EchoRequest) returns (EchoResponse) {
    option (google.api.http) = {
        post: "/echo"
        body: "*"
      };
  }
}

message EchoRequest {
  string ID = 1;
  input.Data In = 2;
}

message EchoResponse {
  string Out = 1;
}
```

If you change `echo.proto` to the following, the error goes away:

```proto
// echo.proto
syntax = "proto3";
package echo;

import "github.com/TuneLab/truss/deftree/googlethirdparty/annotations.proto";
import "input.proto";

service Echo {
  rpc Echo (EchoRequest) returns (EchoResponse) {
    option (google.api.http) = {
        post: "/echo"
        body: "*"
      };
  }
}

message EchoRequest {
  string ID = 1;
  WrappedData In = 2;
}

message EchoResponse {
  string Out = 1;
}

message WrappedData {
  input.Data Datum = 1;
}
```

**Comment by adamryman** [comment]
This is a duplication of https://github.com/TuneLab/truss/issues/201

See my comment there about some of the reasons why we currently have this issue: https://github.com/TuneLab/truss/issues/201#issuecomment-317564509

**Comment by pauln** [comment]
Sorry - I didn't see #201 / connect it with this issue.  That does indeed seem to be what I'm hitting here, though it's interesting that the code formatting warnings only arise if using the imported message directly in a request message - using them directly in a response message doesn't generate any.
