### ISSUE TITLE
Re-running Truss on Windows reverts handlers/handlers.go to template

### ISSUE THREAD

**Issue by pauln** [metaverse/truss#207]
On Windows, Truss doesn't seem to be picking up existing service files when re-run.  As such, it's generating a fresh `handlers/handlers.go` from the template, removing/resetting any handlers which have already been written.

**Comment by adamryman** [comment]
Could you post the output of running the following on an already generated service?

```
truss -v <protofile>...
```

Code that could relate to your issue:

Where the previous service is read from disk into io.Readers: https://github.com/TuneLab/truss/blob/759408035216b6df0741d8ac85f34006433f0e46/cmd/truss/main.go#L194

Where the `handlers.go` file is "Rendered". i.e. where either the handlers file is created or the previous handlers.go is read into an ast and then modified to match the current service definition. 
https://github.com/TuneLab/truss/blob/759408035216b6df0741d8ac85f34006433f0e46/gengokit/handlers/handlers.go#L76

Let us know what progress you make. Thanks!

**Comment by pauln** [comment]
The verbose flag did indeed help me track it down, though it turns out to be a very simple fix: the paths in the map generated by `readPreviousGeneration` were Windows-style.  Running them through `filepath.ToSlash` conforms them to unix-style paths, which matches what's looked for later, which results in the existing files being read in and processed correctly.
