### ISSUE TITLE
Decorate docs markdown as generated files

### ISSUE THREAD

**Issue by zaquestion** [metaverse/truss#214]
To allow github to suppress truss documentation we can use https://github.com/github/linguist formatting rules to decorate our generated docs so there are suppressed in diffs on github.

**Comment by mauricebutts** [comment]
Fairly old issue, this still relevant? Looking for something easy to spin on within Truss.

**Comment by zaquestion** [comment]
Yep, generated docs are gone, but `protoc-gen-swagger` works with truss protos, so thats a pretty good option longer term
