### ISSUE TITLE
Module-auth Security Error

### ISSUE THREAD

**Issue by FotiadisM** [metaverse/truss#321]
After running the example and running `go mod tidy` I get the error:
```
github.com/metaverse/truss@v0.2.0: verifying module: checksum mismatch
	downloaded: h1:aOfjpywT9eQx7ljNmmk5C7GXv/gH70/P2opLc2+sahk=
	sum.golang.org: h1:Ifa1+BVDFHCHIt9K0rVTOlz31kOPwN9mJuoEgrwIzDQ=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

I am on go version: `go1.15.6 linux/amd64`

**Comment by zaquestion** [comment]
Frustrating, this is probably my fault, IIRC I deleted and recreated the `0.2.0` tag several times while tweaking the initial `.goreleaser` file. Thanks for the heads up.

**Comment by zaquestion** [comment]
Thought I did this already... Created a new `v0.2.1` release, hopefully that fixes the issue.

**Comment by zaquestion** [comment]
Believe this is solved, please reopen if you see any issues.
