### ISSUE TITLE
github.com/metaverse/truss@v0.2.0: verifying module: checksum mismatch

### ISSUE THREAD

**Issue by anotherGoogleFan** [metaverse/truss#322]
github.com/metaverse/truss@v0.2.0: verifying module: checksum mismatch
        downloaded: h1:aOfjpywT9eQx7ljNmmk5C7GXv/gH70/P2opLc2+sahk=
        sum.golang.org: h1:Ifa1+BVDFHCHIt9K0rVTOlz31kOPwN9mJuoEgrwIzDQ=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.

**Comment by anotherGoogleFan** [comment]
I checked and find the same issue: https://github.com/metaverse/truss/issues/321 
Can we publish a hotfix to fix this, such as release a temp version, like v0.2.1?

**Comment by zaquestion** [comment]
Sorry, thought I did this already... Created a new `v0.2.1` release, hopefully that fixes the issue.

**Comment by anotherGoogleFan** [comment]
Thanks for solving this so fast.
