### ISSUE TITLE
Define int in proto but got string

### ISSUE THREAD

**Issue by anotherGoogleFan** [metaverse/truss#323]
My proto is like this:
```
syntax = "proto3";

package prototest;

option go_package = ".;prototest";

import "github.com/metaverse/truss/deftree/googlethirdparty/annotations.proto";

service Test {
	rpc Add1(add1Request) returns(Add1Response){
		option (google.api.http) = {
			post: "/add_1"
			body: "*"
		};	
	}
}

message add1Request{
	uint64 ori = 1;
}

message Add1Response{
	uint64 ans = 2;
}
```
AND I post a request:
HTTP POST: http://127.0.0.1:5050/add_1
```
{
    "ori": 15
}
```
I got the response like this:
```
{
    "ans": "16"
}
```
but in proto file, I define ans is an int, not string.
I think the response should be like this:
```
{
    "ans": 16
}
```

**Comment by anotherGoogleFan** [comment]
I tried many times and found that it seems like a bug in ``` github.com/gogo/protobuf/jsonpb ```.
I raise an issue: https://github.com/gogo/protobuf/issues/718

**Comment by zwiedmann-isp** [comment]
hey sorry for the delay, we have a fork of jsonpb in
github.com/metaverse/protobuf -- in my projects i simply use modules to
replace the import and thatll make your int64s numbers again.

**Comment by anotherGoogleFan** [comment]
Thanks a lot. That solve my problem.
