### ISSUE TITLE
go module install error! HELP!!!

### ISSUE THREAD

**Issue by DavidWang666** [metaverse/truss#331]
➜  gowww truss

truss was not built using Makefile.
Please run 'make' inside go import path github.com/metaverse/truss.

Do you want to automatically run 'make' and rerun command:

        $ truss 

? [Y/n] y
FATA[0001] please install truss with make manually: could not find truss directory: cannot find package "github.com/metaverse/truss" in any of:

**Comment by zaquestion** [comment]
Hi David, the easiest way to work around this issue is probably to download the release binary directly: https://github.com/metaverse/truss/releases

Other options: 
If you're on mac you can do `brew install metaverse/tap/truss` 

Otherwise, please follow the install instructions here: https://github.com/metaverse/truss#install

**Comment by DavidWang666** [comment]
thanks!  I've solved it!  off the mod then try again! best wish for you!!

**Comment by chengyayu** [comment]
@zaquestion 

Why not using `go install ....` command? This is in line with the tradition and at the same time convenient.

**Comment by plaird** [comment]
> 
> Other options:
> If you're on mac you can do `brew install metaverse/tab/truss`
> 

There is a typo in @zaquestion comment, it should be _tap_ not _tab_ in the path:

```brew install metaverse/tap/truss```

**Comment by zaquestion** [comment]
@plaird oh gosh, good catch, updated my comment above.

@chengyayu There are a few reasons, partly to ensure versioning information is in the binary. The "please install with make check" is really only checking for this. The other is that our instructions try to guide people down the path that will most easily land them with truss installed and the needed dependencies. If you have suggestions we're absolutely open to them, this hasn't been visited in a while. 

That said, you can install truss with you just need to set those 2 variables to avoid the make check. please not that both of these values are used in the generated code headers, so it's important to be consistent with others you're working with. For example all releases use the same values for these regardless of platform.
```
go install -ldflags '-X "main.version=$(SHA)" -X "main.date=$(VERSION_DATE)"' github.com/metaverse/truss/cmd/truss
```

**Comment by zaquestion** [comment]
Closing as the original issue seems solved
