### ISSUE TITLE
Does it support go module?

### ISSUE THREAD

**Issue by chengyayu** [metaverse/truss#332]
I created a directory named `trussdemo`, and executed `go mod init trussdemo`, then `truss echo.proto`
but got that:

```
FATA[0000] cannot parse input: cannot create .pb.go files: cannot exec protoc with protoc-gen-gogo: protoc exec failed.
protoc output:

/Users/yayu/go/src: warning: directory does not exist.
github.com/metaverse/truss/deftree/googlethirdparty/annotations.proto: File not found.
echo.proto:11:1: Import "github.com/metaverse/truss/deftree/googlethirdparty/annotations.proto" was not found or had errors.
```

**Comment by gethinyan** [comment]
你好，请问这个问题怎么解决

**Comment by gethinyan** [comment]
github.com/metaverse/truss/deftree/googlethirdparty/annotations.proto: File not found.

请问这个问题怎么解决呢？

**Comment by chengyayu** [comment]
> github.com/metaverse/truss/deftree/googlethirdparty/annotations.proto: File not found.
> 
> 请问这个问题怎么解决呢？

这个工具用起来成本太大了。劝退了。

**Comment by zaquestion** [comment]
While truss supports modules on the whole, theres still a limitation that it needs to be in the gopath for protoc to find the annotations file. Do that and you should be good to go

**Comment by gethinyan** [comment]
> > github.com/metaverse/truss/deftree/googlethirdparty/annotations.proto: File not found.
> > 请问这个问题怎么解决呢？
> 
> 这个工具用起来成本太大了。劝退了。

感谢

**Comment by vibhavankhade** [comment]
github.com/metaverse/truss/deftree/googlethirdparty/annotations.proto: File not found.

getting error while running truss *.proto
what is the issue?
