### ISSUE TITLE
How to fix the warning Abc.Xyz is a non-base type specified to be located outside of the body?

### ISSUE THREAD

**Issue by jkaveri** [metaverse/truss#342]
I got the warning below when trying to generate `*.proto` file.

```bash
WARN[0001] Abc.Items is a non-base type specified to be located outside of the body. Non-base types outside the body may result in generated code which fails to compile. 
WARN[0001] Code formatting error, generated service will not build, outputting unformatted code  error="687:1: expected statement, found '%' (and 5 more errors)"
```

And I get compiled error on generated file. `*.pb.go`

My protobuf message look like this

```
	rpc Abc (AbcRequest) returns (AbcResponse) {
		option (google.api.http) = {
		  post: "an-endpoint"
		};
	}

       message AbcRequest {
	string field1 = 1;
	string field2 = 2;
	repeated Item items = 3;
      }

      message Item {
	string name = 1;
    }
```

**Comment by zaquestion** [comment]
It means that you used a type, that may not work reliably as a query param (tho most cases work fine, except nesting at this point). That said assuming based on you going for a POST request, you probably want the params in the body and are confused why you're getting this error.

the pb annotations actually make you specify what goes in the body explicitly. add `body: "*" ` (pretty sure its quoted)
```
option (google.api.http) = {
		  post: "an-endpoint"
                  body: "*" 
		};
```

**Comment by jkaveri** [comment]
Yeah, I debugged truss and found the issue as your suggestion.

Thank @zaquestion
