### ISSUE TITLE
vendor github.com/pmezard/go-difflib/difflib

### ISSUE THREAD

**Issue by hasAdamr** [metaverse/truss#46]
github.com/pmezard/go-difflib/difflib is used in gengokit/httptransport/template_test.go and it is not vendored. @hasLeland can you do that?

**Comment by hasLeland** [comment]
@hasAdamr Yes, that is quite doable!

**Comment by tunezaq** [comment]
Fixed in: https://github.com/TuneLab/go-truss/pull/68
