### ISSUE TITLE
Cannot import generated .pb.go files from multiple services

### ISSUE THREAD

**Issue by adamryman** [metaverse/truss#79]
If I have `foo.proto` and `bar.proto` that generated `foo.pb.go` and `bar.pb.go`, currently, that will also generate two `third_party` directories with various `.pb.go` files that are *protobuf extensions*. Each of these `.pb.go` extension files are imported into a service `foo` that uses service `bar`. This calls an `init()` function in each that registers the extension. This causes a

```
panic: proto: duplicate extension registered: "extension" "id"
```

A solution to this is to switch the import path for these extensions to a common import for all truss services. Google has already created a repo for this https://github.com/google/go-genproto. Though it states it is experimental and could change. We could also create our own repo for this, or store these imports directly in the `truss` repo.

**Comment by hasAdamr** [comment]
Fixed in #92
