### ISSUE TITLE
Proposal: Truss service middlewares

### ISSUE THREAD

**Issue by hasAdamr** [metaverse/truss#94]
Overview: 
1. Have a function that truss does not overwrite where middlewares are added `injectServiceMiddlewares `.
2. Provide options to generate middlewares via flags.
3. User hooks up middlewares in desired order in `injectServiceMiddlewares`.

This uses the `example/echo.proto` for types.

1. Have `echo-server/server_main.go` call a `injectServiceMiddlewares` function to add middlewares
 
	```golang
	// echo-service/echo-server/server_main.go
	...
	// Business domain.
	var service pb.EchoServer
	{
		service = handler.NewService()
		service = injectServiceMiddlewares(service)
	}
	```
	```
	// echo-service/echo-server/wrap.go, next to server_main.go?
	package main
	
	import (
		pb "github.com/TuneLab/go-truss/example/echo-service"
	)
	
	func injectServiceMiddlewares(in pb.EchoServer) pb.EchoServer {
		// TODO: Add middlewares
		return in
	}
	```

2. Generate a empty middleware with truss.
	```
	truss -sm logger [*.proto]
	// or
	truss --servce-middleware logger [*.proto]
	```
	To create:
	```
	// echo-service/middlewares/logger/logger.go
	package logger 
	import (
		"golang.org/x/net/context"
	
		pb "github.com/TuneLab/go-truss/example/echo-service"
	)
	
	type Middleware func(pb.EchoServer) pb.EchoServer
	
	type serviceLogger struct {
		next pb.EchoServer
		// TODO: Add serviceLogger fields 
	}
	
	func (s *serviceLogger) Echo(ctx context.Context, in *pb.EchoRequest) (*pb.EchoResponse, error) {
		// TODO: Implement Echo for serviceLogger
		return s.next.Echo(ctx, in)
	}

	func (s *serviceLogger) Louder(ctx context.Context, in *pb.LouderRequest) (*pb.EchoResponse, error) {
		// TODO: Implement Louder for serviceLogger
		return s.next.Louder(ctx, in)
	}

	func NewServiceLogger( /* TODO: Add serviceLogger constructor params */ ) Middleware {
		return func(next pb.EchoServer) pb.EchoServer {
			return &serviceLogger{
				next: next,
				// TODO: Add serviceLogger constructor params
			}
		}
	}
	```

3. Hooking it up in `wrap.go`
	```
	package main
	
	import (
		pb "github.com/TuneLab/go-truss/example/echo-service"

		// Import something to put into the logger

		logger "github.com/TuneLab/go-truss/example/echo-service/middlewares/logger"
	)

	func injectServiceMiddlewares(in pb.EchoServer) pb.EchoServer {
		in = logger.NewServiceLogger(/* probably put something in here */)(in)

		return in
	}
	```

Files in `echo-service/middlewares` could be watched by truss and updated to match the service definition, much like `echo-service/handlers/server/server_handler.go` is currently.

**Comment by tunezaq** [comment]
Questions / Observations:
- The middleware type will be shared across all middlewares, yes? Thoughts on where to store this? 
- With this proposal all routes need to separately implement the logging/middleware logic.
  - I think this is good as we don't know what requirements may fall on our middle wares.
  - Its pretty easy to define an unexported func (shouldn't be removed on rerun) and call from each of the middlewares.
- For logging and metrics (our first to make middlewares). Much of the logic should be auto-generated as we know what needs to go there and it should be pretty much the same for each route. It makes sense that we put our middlewares after transport, but the unique request types don't do us any favors for generic middlewares.
  - I wonder about placing log info in the context for use in generated logger middlewares (this seems pretty gross as we would have to switch on grpc/httpjson) so probably no.
  - We could place in an `interface{}` and pass straight to some string formatter.
  - Generate each route (perhaps if helped with performance, but not ideal, i'd say)

I wonder if we should have a notion of middlewares owned by truss (always regenerated) and middlewares owned by the user which are managed with the below method.

I like this concept a lot, as it allows management of middlewares to be decoupled from the service. Of course there is risk of the service being regenerated and breaking the middleware, but that would be noticed immediately on build. I think it could be left to the user to handle.

```
truss -m logger [*.proto]
// or
truss --middleware logger [*.proto]
```

**Comment by hasAdamr** [comment]
> - The middleware type will be shared across all middlewares, yes? Thoughts on where to store this?

"A little copying is a better than a little dependency." As this is generated, and `Middleware` is just a function type, I don't think it is a big problem to have `Middleware` redefined. If it was an interface, it would probably be better to be defined in one location, but this is just so we don't have scary looking return arguments. 

```
func (r Recv) AFunc() func(s pb.EchoServer) pb.EchoServer {
// Harder to parse than
type Middleware func(s pb.EchoServer) pb.EchoServer
func (r Recv) AFunc() Middleware {
```

> - With this proposal all routes need to separately implement the logging/middleware logic.

These middlewares are **service** middlewares as go-kit defines them. These can do logging/metrics differently depending on the rpc being called. See [addsvc/service.go](https://github.com/go-kit/kit/blob/master/examples/addsvc/service.go#L99) for an example.

Though go-kit does have middlewares that can be applied to any RPC for access logging / metrics / or even auth (using the context). These are called **endpoint** middlewares. See [addsvc/endpoints.go](https://github.com/go-kit/kit/blob/master/examples/addsvc/endpoints.go#L106) for an example.

> -  Much of the logic should be auto-generated as we know what needs to go there and it should be pretty much the same for each route...

I agree. Here is a proposal. 

```
truss -em logger [*.proto]
// or
truss --endpoint-middleware logger [*.proto]
```

```
...
import "github.com/go-kit/kit/endpoint"

func EndpointLogger(/* TODO: Add a logger */) endpoint.Middleware {
    return func(next endpoint.Endpoint) endpoint.Endpoint {
        return func(ctx context.Context, request interface{}) (response interface{}, err error) {
                // TODO: add logic / or defer logic
                return next(ctx, request)
        }
    }
}
```

As far as hooking them up. I believe we should allow the user to do this in the same way as the `injectServiceMiddlewares` method above. Perhaps `injectEndpointMiddlewares`. This allows the user of truss to select the order they want the middlewares to execute, prehaps important if one of them is auth or something like that.

There is also the consideration of whether all endpoint middlewares should be hooked up automagically to all endpoints. I believe for this proposal that should happen, as if the user wants middlewares that are different pre RPC, then they can use the service middlewares I proposed above.

> - ...of course there is risk of the service being regenerated and breaking the middleware, but that would be noticed immediately on build.

I am partial to the idea that the service middlewares, once generated, are coupled to the service definition and are removed / added as rpc's in the gRPC definition are removed / added. I cannot personally think of a reason not to do this if we are already doing it for the business logic itself. If truss does modify the service middlewares like it modifies the handlers, then the service middlewares will always implement the service interface, even if they are noops by default. Otherwise I imagining the Makefile

```
service: middlewares
    truss *.proto

middlewares:
    truss -m logger *.proto
    truss -m metrics *.proto
    truss -m auth *.proto
```

Though I am up for hearing reasons why this decoupling would be useful and if the reasons are good, I am curious if we should have the handler file coupled as it is currently.

**Comment by tunezaq** [comment]
This seems like a solid approach for endpoint middlewares.

> There is also the consideration of whether all endpoint middlewares should be hooked up automagically to all endpoints.

Agreed, they should and service middlewares can own the more granular case. In my mind and endpoint middleware is something that applies to all of your routes generically which is why its placed where it is in the pipe

> I am partial to the idea that the service middlewares, once generated, are coupled to the service definition and are removed / added as rpc's in the gRPC definition are removed / added.

I agree on service middlewares as any new rpc would require a regeneration of middleware to meet the interface.Endpoint middlewares probably fall into the same case. 

Seems the workflow would be something to the effect of `truss -m logger *.proto` to add a middleware and truss could be smart enough to look for (endpoint/)middlewares in existing projects. In which case removing it would just be a matter of deleting the folder.

I imagine our autogenerated middlewares would just use some reserved middleware names?
for example:

```
truss -em truss-logger *.proto
truss -em truss-metrics-prometheus *.proto
```

I think this is a pretty solid way to do it. I'm curious what @hasIan and @leetune think?
